### ISSUE TITLE
Bug lors du scroll down ou up

### ISSUE THREAD

**Issue by tirgue** [aymericCOUPRIE/Piscine#2]
Lorsque on est sur une page avec une grille de remplissage, le js agit sur les cases à cocher et les fait vibrer lorsque on scroll down ou up et que le menu commence l’animation. Et lorsque l'on clique sur une réponses (genre on clique sur le label A de la question 72), ça nous ramène au début de la page.

**Comment by tirgue** [comment]
i.e : 
view/addTest.php
view/editTest.php
view/respondTest.php

virer les 'for="rep..."'

**Comment by LeoMld** [comment]
fix du problème qui nous fait remonter en haut de page lors de clic sur le label et pour le mini tremblement je ne pourrais rien y faire désolé
